spring.application.name=demo
management.endpoints.web.exposure.include=*
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.shutdown.enabled=false
spring.security.user.name=admin
spring.security.user.password=secret
management.endpoints.web.base-path=/admin/actuator
server.tomcat.threads.max=50
server.tomcat.threads.min=5
resilience4j.ratelimiter.instances.apiRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.apiRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.apiRateLimiter.timeout-duration=0
resilience4j.circuitbreaker.instances.apiCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.apiCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.apiCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.apiCircuitBreaker.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.apiCircuitBreaker.sliding-window-size=10


