spring.application.name=demo
management.endpoints.web.exposure.include=*
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.shutdown.enabled=false
spring.security.user.name=admin
spring.security.user.password=secret
management.endpoints.web.base-path=/admin/actuator


